[workspace]
members = [
    "kernel",

	"lib/vk-hal",

    "lib/vespertine-abi",
    "lib/vespertine-common",
    "lib/vespertine-rt", 
    "lib/vespertine-std", 

	"lib/vespertine-app",
    "lib/vespertine-cli",
	"lib/vespertine-config",

	"userland/auth",
    "userland/hesper", 
    "userland/vlog",
	"userland/vreg",

	"userland/details",
    "userland/dt", 
    "userland/dusk", 
    "userland/ns", 
	"userland/nyx",
	"userland/select",
	"userland/stream",
	"userland/sys",
    "userland/terminal",
	"userland/table",
]

exclude = ["xtask"]

resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"     
lto = true          
codegen-units = 1   
panic = "abort"     
strip = false        
debug = true

[workspace.lints.rust]
dead_code = "allow"
